INSERT	INTO Lecturer(Email, name, Phone, Status, Gender, Birthday, Address, AvatarURL)
VALUES ('khiemtd@fe.edu.vn',N'Tran Duy Khiem',null,1,null,null,null,null),
('linhnh@fe.edu.vn',N'Nguyen Hoang Linh',null,1,null,null,null,null),
('linhvt@fe.edu.vn',N'Vu Tung Linh',null,1,null,null,null,null),
('duongttt@fe.edu.vn',N'To Thi Thuy Duong',null,1,null,null,null,null),
('lanln@fe.edu.vn',N'Luu Nhat Lan',null,1,null,null,null,null),
('mailtn@fe.edu.vn',N'Le Thi Ngoc Mai',null,1,null,null,null,null),
('thanhđt@fe.edu.vn',N'Dinh Tien Thanh',null,1,null,null,null,null),
('tultc@fe.edu.vn',N'La Thi Cam Tu',null,1,null,null,null,null),
('camđth@fe.edu.vn',N'Do Thi Hong Cam',null,1,null,null,null,null),
('kieuta@fe.edu.vn',N'Tran Anh Kieu',null,1,null,null,null,null),
('đoanđc@fe.edu.vn',N'Dang Cong Doan',null,1,null,null,null,null),
('tuendm@fe.edu.vn',N'Nguyen Duy Minh Tue',null,1,null,null,null,null),
('trinhvlb@fe.edu.vn',N'Vu Le Bao Trinh',null,1,null,null,null,null),
('nhi.htm@fe.edu.vn',N'Huynh Thi Mong Nhi',null,1,null,null,null,null),
('khanhkt@fe.edu.vn',N'Kieu Trong Khanh',null,1,null,null,null,null),
('truonglv@fe.edu.vn',N'Le Vu Tuong',null,1,null,null,null,null),
('annđh@fe.edu.vn',N'Ngo Dang Ha An',null,1,null,null,null,null),
('sutv@fe.edu.vn',N'Than Van Su',null,1,null,null,null,null),
('hoangnt@fe.edu.vn',N'Nguyen The Hoang',null,1,null,null,null,null),
('duongvtt@fe.edu.vn',N'Vu Thi Thuy Duong',null,1,null,null,null,null),
('senb@fe.edu.vn',N'Bhaskar Sen',null,1,null,null,null,null),
('danhnt@fe.edu.vn',N'Nguyen Tan Danh',null,1,null,null,null,null),
('đinhmh@fe.edu.vn',N'Mai Hoang Dinh',null,1,null,null,null,null),
('vanttn@fe.edu.vn',N'Than Thi Ngoc Van',null,1,null,null,null,null),
('kiemhh@fe.edu.vn',N'Ho Hoang Kiem',null,1,null,null,null,null),
('thongnt@fe.edu.vn',N'Nguyen Tri Thong',null,1,null,null,null,null),
('ngocttm@fe.edu.vn',N'Truong Thi My Ngoc',null,1,null,null,null,null),
('huongntc@fe.edu.vn',N'Nguyen Thi Cam Huong',null,1,null,null,null,null),
('trucntt@fe.edu.vn',N'Nguyen Thi Thanh Truc',null,1,null,null,null,null),
('phuonglhk@fe.edu.vn',N'Lam Huu Khanh Phuong',null,1,null,null,null,null),
('vanvtt@fe.edu.vn',N'Vo Thi Thanh Van',null,1,null,null,null,null),
('loanltb@fe.edu.vn',N'Le Thi Bich Loan',null,1,null,null,null,null),
('ngocntb@fe.edu.vn',N'Nguyen Thuy Bich Ngoc',null,1,null,null,null,null),
('chaupb@fe.edu.vn',N'Phan Bao Chau',null,1,null,null,null,null),
('tannv@fe.edu.vn',N'Nguyen Viet Tan',null,1,null,null,null,null),
('phuonghtc@fe.edu.vn',N'Hoang Thi Cuc Phuong',null,1,null,null,null,null),
('phuongnqt@fe.edu.vn',N'Nguyễn Quốc Thụy Phương',null,1,null,null,null,null),
('tu2ltc@fe.edu.vn',N'La Thị Cẩm tú2',null,1,null,null,null,null),
('duongdt@fe.edu.vn',N'Dư Tiểu Dương',null,1,null,null,null,null),
('lan2ln@fe.edu.vn',N'Lưu Nhật Lan2',null,1,null,null,null,null),
('nhutnm@fe.edu.vn',N'Trần Ngọc Minh Như',null,1,null,null,null,null),
('quangnc@fe.edu.vn',N'Nguyễn Chính Quang',null,1,null,null,null,null),
('nguyenlnp@fe.edu.vn',N'Lê Ngọc Phương Nguyên',null,1,null,null,null,null);